//update no. 2
var lang = new LanguageManager(
            [{
            langName: "English",
            langCode: "en",
            translations: {
                "appTitle": "Rolling Sky Spritesheet Generator",
                "generateButton": "Generate Spritesheets",
                "selectLang": "Select Language",
                "selectDesign": "Select color mode",
                "lightMode": "Light Mode",
                "darkMode": "Dark Mode",
                "tilesTab": "Tiles",
                "enemyTab": "Enemy",
                "saveTab": "Save/Load",
                "UsedColor": "Color",
                "active": "Active",
                "inactive": "Inactive",
                "front": "Front",
                "back": "Back",
                "recommendedImgSize": "(Recommended image size: ",
                "importImages": "Import texture images",
                "texturePartUnavailable": "This part is unavailable with current top right part settings.",
                "patternColor": "Pattern color",
                "backgroundColor": "Background color",

                "groundSettingsHeading": "Ground settings",
                "groundColor": "Ground tile color",
                "groundLineColor": "Ground tile edge color",
                "groundSideColor": "Ground tile side color",
                "groundEdgeStyle": "Ground tile edge style",
                "groundEdgeStyleNone": "No decoration",
                "groundEdgeStyleCut": "Cut corners",
                "groundEdgeStyleOutline": "With outlines",
                "volcanicGradient": "Use Volcano-style gradient",
                "lineAura": "Line aura",

                "jumppadSettingsHeading": "Jumppad settings",
                "jumppadColor": "Jumppad color",
                "jumppadColorActive": "Active jumppad color",
                "jumppadLineColor": "Jumppad line color",
                "jumppadLineColorActive": "Active jumppad line color",
                "jumppadSideColor": "Jumppad side color",
                "jumppadSideColorActive": "Active jumppad side color",
                "disableActiveJumppadGlow": "Disable gradient in active jumppad",
                "jumppadStyle": "Jumppad pattern",
                "jumppadStyleNormal": "No decoration",
                "jumppadStyleFromRS": "Rolling Sky",
                "jumppadStyleCut": "Cut corners",
                "jumppadStyleGrid": "Grid lines",
                "jumppadStyleSquares": "Squares(sky castle)",
                "jumppadStyleChina": "Spiral Patterns",
                "jumppadStyleChecker": "Checkerboard",
                "jumppadStyleHexagons": "Hexagons",
                "jumppadStyleFanmade": "Fanmade",
                "jumppadStyleCave": "Circle(Cave)",
                "jumppadStyleChemistry": "Grid+square(Chemistry)",
                "jumppadStyleDynamicHill": "Squares(Dynamic Hill)",
                "jumppadStyleWanderingHabits": "Kanji \"放浪癖\"(Low Life)",
                "jumppadStyleCitrus": "Citrus(Cotton Candy)",
                "jumppadStyleRollingWorld": "Circle+rhombus(Rolling World)",
                "jumppadCustomizationDefaultContent": "No customization for this jumppad pattern available",
                "fanmadePatternStyleDisclaimer": "この模様は本家ローリングスカイには存在しない模様であり、あくまでもこのツール作者が似せて作ったものなので正確な寸法では(多分)ありません。",
                "squaresJumppadInactiveInner": "Jumppad square color(inner)",
                "squaresJumppadInactiveOuter": "Jumppad square color(outer)",
                "squaresJumppadActiveInner": "Active jumppad square color(inner)",
                "squaresJumppadActiveOuter": "Active jumppad square color(outer)",
                "activeOnlyGrid": "Active only",
                "inactiveGridColor": "Inactive grid color",
                "gridJumppadInactiveInner": "Inactive jumppad pattern color",
                "checkerJumppadInactiveEdge": "Edge square color(inactive)",
                "checkerJumppadActiveEdge": "Edge square color(active)",
                "inactiveJumppadGlow": "Inactive jumppad glow",

                "generalVariationHeading": "General color variation settings",
                "generalVariation1": "Variation 1",
                "generalVariation2": "Variation 2",
                "generalVariation3": "Variation 3",
                "generalVariation4": "Variation 4",

                "fragileSettingHeading": "Fragile Settings",
                "fragileColor": "Fragile color",
                "fragileActiveColor": "Fragile color(active)",
                "fragileLineColor": "Fragile edge color",
                "fragileActiveLineColor": "Fragile edge color(active)",
                "fragileSideColor": "Fragile side color",
                "fragileActiveSideColor": "Fragile side color(active)",
                "fragileStyle": "Fragile pattern",
                "fragileStylePlain": "No patterns",
                "fragileStyleStripes": "Striped outlines",
                "fragileStyleCave": "Decorated corner(Cave)",
                "fragileStyleBubbles": "Hexagon bubbles(Chemistry)",
                "fragileCustomizationDefaultContent": "No customization for this fragile pattern available",
                "fragileStripeColor": "Stripe Color",
                "fragileActiveStripeColor": "Stripe Color(active)",

                "moverSettingHeading": "Mover settings",
                "moverSameColor": "Use the same color for movers/automovers and ground",
                "moverLineColor": "Mover line color",
                "moverAutoLineColor": "Automover line color",
                "moverOutlineColor": "Mover outline color",
                "moverAutoOutlineColor": "Automover outline color",
                "moverOutlineBorderColor": "Mover outline border color",
                "moverAutoOutlineBorderColor": "Automover outline border color",
                "moverSideColor": "Mover side color",
                "moverAutoSideColor": "Automover side color",
                "moverActiveArrowColor": "Active mover arrow color",
                "moverAutoActiveArrowColor": "Active automover arrow color",
                "moverActiveArrowBorderColor": "Active mover arrow border color",
                "moverAutoActiveArrowBorderColor": "Active automover arrow border color",
                "moverArrowTopColor": "Arrow top color",
                "moverArrowUpperSideColor": "Arrow upper side color",
                "moverArrowSideColor": "Arrow side color",

                "midGroundSettingHeading": "MidGround settings",
                "midGroundTopColor": "Top color",
                "midGroundBottomColor": "Bottom color",
                "midGroundWindows": "Add windows",
                "midGroundWindowsTop": "Windows top color",
                "midGroundWindowsMiddle": "Windows middle color",
                "midGroundWindowsBottom": "Windows bottom color",
                
                "finishLineSettingHeading": "Finish line settings",
                "finishLineColorA": "Color A",
                "finishLineColorB": "Color B",
                "finishLineInactive": "Inactive",
                "finishLineActive": "Active",
                "finishLineActiveLine": "Active edge line",

                "gemSettingHeading": "Low quality gem settings",
                "gemColor": "Gem color",
                "gemLineColor": "Gem line color",
                "gemLightColor": "Gem lighter color",

                //ここからEnemy
                "objectPreview": "Object preview",

                "lightSettingHeading": "Light setting (A)",
                "radialLightSettingHeading": "Radial Light (A1)",
                "lightOuterColor": "Outer Color",
                "lightInnerColor": "Inner Color",
                "linearLightSettingHeading": "Linear Light (A2~4)",
                "linearLightSameColor": "Use the same color for all types of lights",
                "linearLightASettingHeading": "Linear Light A(A2): Used for laser",
                "linearLightBSettingHeading": "Linear Light B(A3): Used for spotlight, UFO, Sci-Tech laser",

                "topRightSettingHeading": "Primary theme area setting (B)",
                "topRightType": "Usage",

                "topRightFloater": "Floater (fl)",
                "floaterMainColor": "Main color (fl1)",
                "floaterSpikeInnerColor": "Spike inner color (fl2)",
                "floaterInactiveEdgeColor": "Inactive edge color (fl3)",
                "floaterActiveEdgeColor": "Active edge color (fl4)",

                "topRightCrystal": "Crystal (cr)",
                "russianTowerTop": "Russian tower top",
                "russianTowerMiddleTop": "Russian tower middle top face",
                "russianTowerLowerTop": "Russian tower lower top face",
                "crystalInnerColor": "Inner Color",
                "crystalOuterColor": "Outer Color",
                "tetriminoOuterSameColor": "Use the same outer color for all tetrimino parts",
                "tetriminoGradient": "Apply gradients to all tetrimino parts",
                "crystalCollection1": "Color 1(cr4)",
                "crystalCollection2": "Color 2(cr5)",
                "crystalCollection3": "Color 3(cr6)",
                "crystalCollection4": "Color 4(cr7)",
                "crystalCollection5": "Color 5(cr8)",
                "crystalCollection6": "Color 6(cr9)",
                "crystalCollection7": "Color 7(cr10)",
                "crystalCollection8": "Color 8(cr11)",
                "tetriminoes": "Tetriminoes",
                "crystalGate": "Crystal gate",
                "iceCube": "Ice cube",
                "crystalTree": "Crystal trees",
                "russianTowers": "Russian towers",

                "topRightGeometry": "Geometry (cb)",
                "cubeStructure": "Cube structure",
                "cubeStructureType": "Pattern",
                "cubeStructureOriginal": "Original",
                "cubeStructureTop": "Top (cb1)",
                "cubeStructureFront": "Front (cb2)",
                "cubeStructureFrame": "Frame",
                "largeOctahedronSettingHeading": "Large octahedron",
                "largeOctahedronTriangleSideA": "Triangle inner side color A",
                "largeOctahedronTriangleSideB": "Triangle inner side color B",
                "spinCubeSettingHeading": "Spinning Cubes",
                "spinCubeType": "Front rhombus pattern",
                "spinCubeOriginal": "Original",
                "originalSpinCubeColorA": "Upper left, lower right",
                "originalSpinCubeColorB": "Lower left, upper right",
                "frontRhombus": "Import here",
                
                "subBSettingHeading": "Secondary theme area setting",
                "subBType": "Usage",
                "subBNoPattern": "No pattern",
                "subBClassicalRoller": "Classical roller",
                "doubleLines": "Double lines",
                "subBDesert": "Palm tree trunk",
                
                
                "flipTileSettingHeading": "Flipper tile setting",
                "flipTileType": "Flipper tile type",
                "flipperObverse": "Obverse",
                "flipperReverse": "Reverse",
                "flipTileCube": "Triangles (Cube)",
                "flipTileChecker": "Checkered (Poker)",
                "flipTileHolly": "Holly flower (Varying Christmas)",
                "flipTileRhombus": "Rhombus (Spring Festival)",
                "flipTileSquares": "Squares (Microchip)",
                "flipTileULines": "U-shaped lines (Psychedelic Music)",
                "flipTileStar": "Five-pointed star (The 4th Anniversary)",
                "flipTileSemicircles": "Semicircles (Kepler's Dream)",
                "flipTileCits": "c",
                "cubeFlipperColorA": "Color A",
                "cubeFlipperColorB": "Color B",
                "checkerFlipperColorA": "Far left - near right",
                "checkerFlipperColorB": "Near left - far right",
                "rhombusFlipperRhombusColor": "Rhombus",
                "demisemicirclesFlipperCenterColor": "Center",
                "demisemicirclesFlipperColorB": "Far left - near right",
                "demisemicirclesFlipperColorC": "Near left - far right",
                "hollyFlipperPetalColor1": "Petals A",
                "hollyFlipperPetalColor2": "Petals B",
                "hollyFlipperSpotColor": "Spots",
                "flipperFrameColor": "Frame",
                "flipperSideColor": "Flipper side color",
                
                "mainStripeSettingHeading": "Main stripe setting (C)",
                "mainStripeThickness": "Main stripe thickness",
                "mainStripeThick": "Thick (T=25, I=46.22)",
                "mainStripeNormal": "Normal (T=13, I=25.77)",
                "mainStripeThin": "Thin (T=10, I=25.75)",
                "mainStripeCustom": "Custom",
                "mainStripeCustomThickness": "Thickness",
                "mainStripeCustomInterval": "Interval",
                "mainStripeCustomStart": "Start position",
                "mainStripeBack": "Back",
                "mainStripeFront": "Front",
                "mainStripeColorSteps": "Color steps",
                "mainStripe1Tone": "Single tone",
                "mainStripe2Tones": "Two tones",
                "mainStripe3TonesThin": "Three tones (Thin middle part)",
                "mainStripe3TonesThick": "Three tones (Thick middle part)",
                "mainStripeTone1": "Tone 1",
                "mainStripeTone2": "Tone 2",
                "mainStripeTone3": "Tone 3",
                "addCenterLine": "Add center line",

                "middleLeftSettingHeading": "Main color A setting (D)",
                "middleRightSettingHeading": "Main color B setting (E)",
                "middleLeftTone1": "Tone 1 (D1)",
                "middleLeftTone2": "Tone 2 (D2)",
                "middleLeftTone3": "Tone 3 (D3)",
                "middleLeftTone4": "Tone 4 (D4)",
                "middleLeftTone5": "Tone 5 (D5)",
                "middleLeftTone6": "Tone 6 (D6)",
                "middleLeftTone7": "Tone 7 (E7)",
                "middleRightTone1": "Tone 1 (E1)",
                "middleRightTone2": "Tone 2 (E2)",
                "middleRightTone3": "Tone 3 (E3)",
                "middleRightTone4": "Tone 4 (E4)",
                "middleRightTone5": "Tone 5 (E5)",
                "middleRightTone6": "Tone 6 (E6)",
                "face": "Face",
                "line": "Line",
                
                "bottomLeftSettingHeading": "Bottom left setting (F)",
                "BLLightColor": "Light",
                "BLMediumColor": "Medium",
                "BLDarkColor": "Dark",
                "bottomLeftNormal": "Normal",
                "bottomLeftSkyCastle": "Sky castle",
                "BLGradation": "Gradation",
                "BLGradationTop": "Gradation top",
                "BLGradationBottom": "Gradation bottom",
                "BLStripes": "Stripes",
                "BLStripeWidth": "Stripe width",
                "fillBottommost": "Fill bottommost part",
                "rowRemovalConfirmation": "Are you sure you want to remove this row?",
                "skyCastleBLTriangleTip": "Triangle tips",
                
                "bottomRightSettingHeading": "Bottom right setting (G)",
                "bottomRightRiserOutlined": "Outlined riser",
                "bottomRightRiserRound": "Round riser",
                "riserTopMain": "Riser top primary color",
                "riserTopInactiveLine": "Riser top secondary color (inactive)",
                "riserTopActiveLine": "Riser top secondary color (active)",
                "riserTopInner": "Riser top inner:",
                "riserTopLine": "Riser top middle line:",
                "riserTopOuter": "Riser top outer",
                "riserInactive": "inactive",
                "riserActive": "active",
                "riserLine": "Riser line",
                "BLStripeLine": "Put lines between stripes",
                "useRiserLine": "Use riser edge line",

                "saveTheme": "Save project in JSON format",
                "themeName": "Project name(only used for the file name)",
                "loadSavedTheme": "Load saved project",

                "filenameGeneral": "General",
                "filenameFragile": "Fragile",
                "filenameFragileActive": "FragileActive",
                "filenameMover": "Mover",
                "filenameMoverAuto": "MoverAuto",
                "filenameEnemy": "Enemy",
                "filenameBall": "Ball",

                "canvasAltText": "Canvas not available",
                "fileLoading": "Loading file...",
                "loadFileComplete": "Successfully loaded the file",
                "loadError": "An error occured while loading the file",
                "loadSavedThemeConfirmation": "Are you sure you want to replace current setting?",
                "imgRemoveConfirmation": "Are you sure you want to remove this imported image?",
                
                "downloadGeneral": "Download General",
                "downloadFragile": "Download Fragile",
                "downloadFragileActive": "Download FragileActive",
                "downloadMover": "Download Mover",
                "downloadMoverAuto": "Download MoverAuto",
                "downloadEnemy": "Download Enemy"
            }
                },

        {
            langName: "日本語",
            langCode: "ja",
            translations: {
                "appTitle": "ローリングスカイテクスチャメーカー",
                "generateButton": "テクスチャ画像生成",
                "selectLang": "言語を選択",
                "selectDesign": "デザインモードを選択",
                "lightMode": "ライトモード",
                "darkMode": "ダークモード",
                "tilesTab": "床",
                "enemyTab": "障害物",
                "saveTab": "保存",
                "UsedColor": "使用色",
                "active": "起動時",
                "inactive": "未起動時",
                "front": "手前",
                "back": "奥",
                "recommendedImgSize": "(推奨画像サイズ: ",
                "importImages": "画像をインポート",
                "texturePartUnavailable": "現在の右上部分の設定ではこの領域は使用できません。",
                "patternColor": "模様色",
                "backgroundColor": "背景色",

                "groundSettingsHeading": "普通床の設定",
                "groundColor": "普通床の色",
                "groundLineColor": "普通床の線の色",
                "groundSideColor": "普通床の側面の色",
                "groundEdgeStyle": "普通床の端の形",
                "groundEdgeStyleNone": "装飾無し",
                "groundEdgeStyleCut": "角落ち",
                "groundEdgeStyleOutline": "縁取り有り",
                "volcanicGradient": "火山風グラデーション",
                "lineAura": "線を2重にする",

                "jumppadColor": "ジャンプ床の色",
                "jumppadColorActive": "起動時のジャンプ床の色",
                "jumppadLineColor": "ジャンプ床の線の色",
                "jumppadLineColorActive": "起動時のジャンプ床の線の色",
                "jumppadSideColor": "ジャンプ床の側面の色",
                "jumppadSideColorActive": "起動時のジャンプ床の側面の色",
                "disableActiveJumppadGlow": "起動時のジャンプ床面部分の発光を無効化",
                "jumppadSettingsHeading": "ジャンプ床の設定",
                "jumppadStyle": "ジャンプ床の模様",
                "jumppadStyleNormal": "装飾無し",
                "jumppadStyleFromRS": "ローリング・スカイ",
                "jumppadStyleCut": "角落ち",
                "jumppadStyleGrid": "格子模様",
                "jumppadStyleSquares": "四角形(天空の城)",
                "jumppadStyleChina": "中国風渦巻き模様",
                "jumppadStyleChecker": "市松模様",
                "jumppadStyleHexagons": "六角形模様",
                "jumppadStyleFanmade": "ファンメイド",
                "jumppadStyleCave": "円形(洞窟)",
                "jumppadStyleChemistry": "格子+四角(化学)",
                "jumppadStyleDynamicHill": "四角(ダイナミックな丘)",
                "jumppadStyleWanderingHabits": "「放浪癖」(Low Life)",
                "jumppadStyleCitrus": "柑橘断面(キャンディフロス)",
                "jumppadStyleRollingWorld": "円+四角(Rolling World)",
                "jumppadCustomizationDefaultContent": "このジャンプ床の模様にはカスタマイズオプションがありません",
                "fanmadePatternStyleDisclaimer": "この模様は本家ローリングスカイには存在しない模様であり、あくまでもこのツール作者が似せて作ったものなので正確な寸法では(多分)ありません。",
                "squaresJumppadInactiveInner": "四角の内側の色",
                "squaresJumppadInactiveOuter": "四角の枠の色",
                "squaresJumppadActiveInner": "四角の内側の色(起動時)",
                "squaresJumppadActiveOuter": "四角の枠の色(起動時)",
                "activeOnlyGrid": "起動時のみ",
                "inactiveGridColor": "非起動時の格子模様の色",
                "gridJumppadInactiveInner": "非起動時の格子模様の色",
                "checkerJumppadInactiveEdge": "非起動時の端側の四角の色",
                "checkerJumppadActiveEdge": "起動時の端側の四角の色",
                "inactiveJumppadGlow": "非起動時のジャンプ床面部分の発光",

                "generalVariationHeading": "補助パレットの設定",
                "generalVariation1": "変化1",
                "generalVariation2": "変化2",
                "generalVariation3": "変化3",
                "generalVariation4": "変化4",

                "fragileSettingHeading": "ガラス床の設定",
                "fragileColor": "ガラス床の色",
                "fragileActiveColor": "ガラス床の色(起動後)",
                "fragileLineColor": "ガラス床の線の色",
                "fragileActiveLineColor": "ガラス床の線の色(起動後)",
                "fragileSideColor": "ガラス床の側面の色",
                "fragileActiveSideColor": "ガラス床の側面の色(起動後)",
                "fragileStyle": "模様",
                "fragileStylePlain": "模様無し",
                "fragileStyleStripes": "縞模様の縁",
                "fragileStyleCave": "角の装飾",
                "fragileStyleBubbles": "六角形の泡",
                "fragileCustomizationDefaultContent": "このガラス床の模様にはカスタマイズオプションがありません",
                "fragileStripeColor": "縞模様の色",
                "fragileActiveStripeColor": "縞模様の色(起動時)",

                "moverSettingHeading": "移動床の設定",
                "moverSameColor": "移動床の色に通常床の色を流用する",
                "moverLineColor": "発動床の線の色",
                "moverAutoLineColor": "連動床の線の色",
                "moverOutlineColor": "発動床の縁の色",
                "moverAutoOutlineColor": "連動床の縁の色",
                "moverOutlineBorderColor": "発動床の縁の線の色",
                "moverAutoOutlineBorderColor": "連動床の縁の線の色",
                "moverSideColor": "発動床の側面の色",
                "moverAutoSideColor": "連動床の側面の色",
                "moverActiveArrowColor": "起動した発動床の三角の色",
                "moverAutoActiveArrowColor": "起動した連動床の三角の色",
                "moverActiveArrowBorderColor": "起動した発動床の三角の縁の色",
                "moverAutoActiveArrowBorderColor": "起動した連動床の三角の縁の色",
                "moverArrowTopColor": "移動床三角の土台上面",
                "moverArrowUpperSideColor": "移動床三角の端の切り込み面",
                "moverArrowSideColor": "移動床三角の側面",

                "midGroundSettingHeading": "通過オブジェクトの設定",
                "midGroundTopColor": "上端の色",
                "midGroundBottomColor": "下端の色",
                "midGroundWindows": "窓の追加",
                "midGroundWindowsTop": "窓上端",
                "midGroundWindowsMiddle": "窓中央",
                "midGroundWindowsBottom": "窓下端",
                
                "finishLineSettingHeading": "ゴールテープの設定",
                "finishLineColorA": "色A",
                "finishLineColorB": "色B",
                "finishLineInactive": "到達前",
                "finishLineActive": "到達後",
                "finishLineActiveLine": "到達後のブロック辺の線",

                "gemSettingHeading": "低品質ジェムの設定",
                "gemColor": "基本色",
                "gemLineColor": "線の色",
                "gemLightColor": "明るい色",

                "ballSettingHeading": "ボールの設定",
                "ballOuter": "外側の色",
                "ballInner": "内側の色",

                //ここからEnemy
                "objectPreview": "プレヴュー",

                "lightSettingHeading": "光の設定 (A)",
                "radialLightSettingHeading": "円形の光 (A1)",
                "lightOuterColor": "外側",
                "lightInnerColor": "内側",
                "linearLightSettingHeading": "線形の光 (A2~4)",
                "linearLightSameColor": "全種類の光を同じ色にする",
                "linearLightASettingHeading": "線形の光A (A2): 通常レーザーで使用",
                "linearLightBSettingHeading": "線形の光B (A3): スポットライト, UFO, 科学技術レーザーで使用",

                "topRightSettingHeading": "右上の設定 (B)",
                "topRightType": "使用方法",

                "topRightFloater": "星 (fl)",
                "floaterMainColor": "基本色 (fl1)",
                "floaterSpikeInnerColor": "棘の内側 (fl2)",
                "floaterInactiveEdgeColor": "起動前の縁 (fl3)",
                "floaterActiveEdgeColor": "起動後の縁 (fl4)",

                "topRightCrystal": "結晶 (cr)",
                "russianTowerTop": "ロシア風タワー頂点 (cr1)",
                "russianTowerMiddleTop": "ロシア風タワーの中間の上面 (cr2)",
                "russianTowerLowerTop": "ロシア風タワーの下の方の上面 (cr3)",
                "crystalInnerColor": "内側",
                "crystalOuterColor": "外側",
                "tetriminoOuterSameColor": "全てのテトリミノの枠線を同じ色にする",
                "tetriminoGradient": "全てのテトリミノにグラデーションを適用する",
                "crystalCollection1": "パレット色1(cr4)",
                "crystalCollection2": "パレット色2(cr5)",
                "crystalCollection3": "パレット色3(cr6)",
                "crystalCollection4": "パレット色4(cr7)",
                "crystalCollection5": "パレット色5(cr8)",
                "crystalCollection6": "パレット色6(cr9)",
                "crystalCollection7": "パレット色7(cr10)",
                "crystalCollection8": "パレット色8(cr11)",
                "tetriminoes": "テトリミノ",
                "crystalGate": "結晶門",
                "iceCube": "出現氷塊",
                "crystalTree": "結晶の木",
                "russianTowers": "ロシア風の塔",

                "topRightGeometry": "幾何 (cb)",
                "cubeStructure": "構造物キューブ",
                "cubeStructureType": "模様",
                "cubeStructureOriginal": "本家と同じ",
                "cubeStructureTop": "上面",
                "cubeStructureFront": "手前面",
                "cubeStructureFrame": "枠",
                "largeOctahedronSettingHeading": "巨大八面体",
                "largeOctahedronTriangleSideA": "上側の面の内部三角形の色 A",
                "largeOctahedronTriangleSideB": "上側の面の内部三角形の色 B",
                "spinCubeSettingHeading": "回転立方体",
                "spinCubeType": "手前面の模様",
                "spinCubeOriginal": "基本",
                "originalSpinCubeColorA": "左上と右下",
                "originalSpinCubeColorB": "右上と左下",
                "frontRhombus": "ここに画像をインポート",
                
                "subBSettingHeading": "第二テーマ領域設定",
                "subBType": "使用方法",
                "subBNoPattern": "模様無し(単色)",
                "subBClassicalRoller": "初代車輪",
                "doubleLines": "線を倍増",
                "subBDesert": "ヤシの木の幹",
                
                "flipTileSettingHeading": "翻転床",
                "flipTileType": "模様タイプ",
                "flipperObverse": "表",
                "flipperReverse": "裏",
                "flipTileCube": "X形 (立方)",
                "flipTileChecker": "市松模様 (トランプ)",
                "flipTileHolly": "花模様 (幻のクリスマス)",
                "flipTileRhombus": "四角模様 (春節)",
                "flipTileSquares": "四角模様 (マイクロチップ)",
                "flipTileULines": "U字型の線 (幻想的なサウンド)",
                "flipTileStar": "星型 (四周年)",
                "flipTileSemicircles": "円形 (ケプラーの夢)",
                "flipTileCits": "cits",
                "cubeFlipperColorA": "前後の枠と左右の内側三角",
                "cubeFlipperColorB": "左右の枠と前後の内側三角",
                "checkerFlipperColorA": "左奥と右手前",
                "checkerFlipperColorB": "右奥と左手前",
                "rhombusFlipperRhombusColor": "四角形",
                "demisemicirclesFlipperCenterColor": "中央",
                "demisemicirclesFlipperColorB": "左奥と右手前",
                "demisemicirclesFlipperColorC": "右奥と左手前",
                "hollyFlipperPetalColor1": "花びら",
                "hollyFlipperPetalColor2": "中央と花びらの縁",
                "hollyFlipperSpotColor": "点",
                "flipperFrameColor": "枠",
                "flipperSideColor": "側面の色",
                
                "mainStripeSettingHeading": "基本縞模様の設定 (C)",
                "mainStripeThickness": "縞の太さ",
                "mainStripeThick": "太い (T=25, I=46.22)",
                "mainStripeNormal": "普通 (T=13, I=25.77)",
                "mainStripeThin": "細い (T=10, I=25.75)",
                "mainStripeCustom": "カスタム",
                "mainStripeCustomThickness": "太さ",
                "mainStripeCustomInterval": "周期",
                "mainStripeCustomStart": "開始左右位置",
                "mainStripeBack": "背景",
                "mainStripeFront": "縞",
                "mainStripeColorSteps": "色段階数",
                "mainStripe1Tone": "1段階",
                "mainStripe2Tones": "2段階",
                "mainStripe3TonesThin": "3段階 (太い中央部分)",
                "mainStripe3TonesThick": "3段階 (細い中央部分)",
                "mainStripeTone1": "トーン 1",
                "mainStripeTone2": "トーン 2",
                "mainStripeTone3": "トーン 3",
                "addCenterLine": "中央に細い線を入れる",

                "middleLeftSettingHeading": "立体基本色Aの設定 (D)",
                "middleRightSettingHeading": "立体基本色Bの設定 (E)",
                "middleLeftTone1": "トーン1 (D1)",
                "middleLeftTone2": "トーン2 (D2)",
                "middleLeftTone3": "トーン3 (D3)",
                "middleLeftTone4": "トーン4 (D4)",
                "middleLeftTone5": "トーン5 (D5)",
                "middleLeftTone6": "トーン6 (D6)",
                "middleLeftTone7": "トーン7 (E7)",
                "middleRightTone1": "トーン1 (E1)",
                "middleRightTone2": "トーン2 (E2)",
                "middleRightTone3": "トーン3 (E3)",
                "middleRightTone4": "トーン4 (E4)",
                "middleRightTone5": "トーン5 (E5)",
                "middleRightTone6": "トーン6 (E6)",
                "face": "面",
                "line": "線",
                
                "bottomLeftSettingHeading": "基本側面の設定 (F)",
                "BLLightColor": "明",
                "BLMediumColor": "中",
                "BLDarkColor": "暗",
                "bottomLeftNormal": "一般",
                "bottomLeftSkyCastle": "天空の城式",
                "BLGradation": "グラデーション",
                "BLGradationTop": "グラデーション上端",
                "BLGradationBottom": "グラデーション下端",
                "BLStripes": "線",
                "BLStripeWidth": "帯の幅",
                "BLStripeLine": "帯の間に線を入れる",
                "fillBottommost": "左下の隅を使用する",
                "rowRemovalConfirmation": "この帯を削除しますか?",
                "skyCastleBLTriangleTip": "三角形の小片",
                
                "bottomRightSettingHeading": "右下の設定 (G)",
                "bottomRightRiserOutlined": "Riser A",
                "bottomRightRiserRound": "Riser B",
                "riserTopMain": "Riser上面基本色",
                "riserTopInactiveLine": "Riser上面アクセント色(未起動)",
                "riserTopActiveLine": "Riser上面アクセント色(起動)",
                "riserTopInner": "Riser上面内側:",
                "riserTopLine": "Riser上面帯:",
                "riserTopOuter": "Riser上面外側:",
                "riserLine": "Riser上面線",
                "riserInactive": "未起動時",
                "riserActive": "起動時",
                "useRiserLine": "Riserの縁に線を描画",

                "saveTheme": "テーマをJSON形式で保存",
                "themeName": "テーマの名前(保存されたファイルの名前にのみ使用されます。)",
                "loadSavedTheme": "保存したテーマを読み込む",

                "filenameGeneral": "General(通常床・立体)",
                "filenameFragile": "Fragile(ガラス床)",
                "filenameFragileActive": "FragileActive(落下中のガラス床)",
                "filenameMover": "Mover(発動床)",
                "filenameMoverAuto": "MoverAuto(連動床)",
                "filenameEnemy": "Enemy(障害物)",
                "filenameBall": "Ball(ボール)",

                "canvasAltText": "Canvasが使用できません。",
                "fileLoading": "ファイルを読み込み中",
                "loadFileComplete": "ファイルの読み込みに成功しました",
                "loadError": "エラーが発生しました",
                "loadSavedThemeConfirmation": "既にある設定を削除しますか?",
                "imgRemoveConfirmation": "インポート画像を削除しますか?",
                
                "downloadGeneral": "Generalをダウンロード",
                "downloadFragile": "Fragileをダウンロード",
                "downloadFragileActive": "FragileActiveをダウンロード",
                "downloadMover": "Moverをダウンロード",
                "downloadMoverAuto": "MoverAutoをダウンロード",
                "downloadEnemy": "Enemyをダウンロード"
            }
                }
            ]);

window.addEventListener("load", function () {
    lang.initSelectBox(document.getElementById("languageSelectBox"), "en");
    lang.useLanguage("en");
}, true);
